pipeline{

    agent any

    stages {

        stage ('Compile Stage') {

            steps {

                    sh 'mvn -f jenkins-pipeline-cucumber-example-feature-test-pipeline-cucumber/pom.xml clean install'


            }
        }
    stage ('Test Stage') {

            steps {


                    sh 'mvn -f jenkins-pipeline-cucumber-example-feature-test-pipeline-cucumber/pom.xml test'


            }
        }


        stage ('Cucumber Reports') {

            steps {
                cucumber buildStatus: "UNSTABLE",
                    fileIncludePattern: "**/cucumber.json",
                    jsonReportDirectory: 'target'

            }

        }

    }

}